### ISSUE TITLE
Income (wages and salary) 1950 -Can only search on 10,000+ or not

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#198] opened 2023-04-01 13:39 UTC
There is a box to check for 10,000+, the only options are to chose whether it contains that amount, or "is not" etc. but you can't sort on ranges or other amounts.

**Comment by dfurber** [comment] 2023-04-02 20:57
Yep it looks problematic. And also like I'm going to have to rebuild the search, so I'll fix it then.

**Comment by dfurber** [comment] 2023-04-30 23:42
I noticed this after creating a similar issue. And now 1940 behaves the same way. The problem is that the number isn't stored as `1234` but as `"1234"`, i.e. as a string. That was the price of being able to select `Un` and `P6` and `$10,000+`.

**Comment by dfurber** [comment] 2023-04-30 23:42
Closed in favor of the issue I logged.

**Closed as completed by dfurber** 2023-04-30 23:42 UTC
